import { normalizeDeploymentConfig, type DeploymentConfig, type NormalizedDeploymentConfig } from './config.js';
import { redactText } from './redact.js';

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function normalized(config: DeploymentConfig | NormalizedDeploymentConfig): NormalizedDeploymentConfig {
  return 'remoteLinuxDir' in config ? config : normalizeDeploymentConfig(config);
}

export function commandCreateRemoteDir(config: DeploymentConfig | NormalizedDeploymentConfig): string {
  const plan = normalized(config);
  return `mkdir -p ${shellQuote(plan.remoteLinuxDir)}`;
}

export function commandChmodScripts(config: DeploymentConfig | NormalizedDeploymentConfig): string {
  const plan = normalized(config);
  const scripts = ['install.sh', 'healthcheck.sh', 'backup.sh', 'restore.sh', 'upgrade.sh', 'prepare-directories.sh']
    .map((script) => shellQuote(`${plan.remoteLinuxDir}/${script}`))
    .join(' ');
  return `chmod +x ${scripts}`;
}

export function commandRunInstallSelfCheck(config: DeploymentConfig | NormalizedDeploymentConfig): string {
  const plan = normalized(config);
  return `cd ${shellQuote(plan.remoteLinuxDir)} && ./install.sh --self-check`;
}

export function commandRunInstall(config: DeploymentConfig | NormalizedDeploymentConfig): string {
  const plan = normalized(config);
  if (plan.dryRun) return `cd ${shellQuote(plan.remoteLinuxDir)} && ./install.sh --dry-run`;
  if (plan.runMigrations) return `cd ${shellQuote(plan.remoteLinuxDir)} && ./install.sh --migrate`;
  return `cd ${shellQuote(plan.remoteLinuxDir)} && ./install.sh`;
}

export function commandRunHealthcheck(config: DeploymentConfig | NormalizedDeploymentConfig): string {
  const plan = normalized(config);
  return `cd ${shellQuote(plan.remoteLinuxDir)} && ./healthcheck.sh`;
}

export function generateRedactedRemoteEnv(config: DeploymentConfig): string {
  return redactText('Remote .env is not generated by this MVP. Copy .env.example on the server and fill secrets there.', config);
}

export function plannedRemoteCommands(config: DeploymentConfig | NormalizedDeploymentConfig): string[] {
  return [
    commandCreateRemoteDir(config),
    commandChmodScripts(config),
    commandRunInstallSelfCheck(config),
    commandRunInstall(config),
  ];
}
